# Generated by Django 4.2 on 2025-07-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(db_index=True, default='view', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FileShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for permanent link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-upload_date'], 'verbose_name': 'File Upload', 'verbose_name_plural': 'File Uploads'},
        ),
        migrations.AddField(
            model_name='fileupload',
            name='description',
            field=models.TextField(blank=True, help_text='Optional file description', null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time file was accessed', null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(help_text='Upload file (max 100MB)', upload_to=files.models.user_directory_path, validators=[files.models.validate_file_size, files.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_hash',
            field=models.CharField(db_index=True, help_text='SHA256 hash of file content for duplicate detection', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_size',
            field=models.BigIntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(db_index=True, help_text='File extension/type', max_length=10),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='original_filename',
            field=models.CharField(help_text='Original filename as uploaded by user', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_by', '-upload_date'], name='files_fileu_uploade_b75d94_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['original_filename'], name='files_fileu_origina_8a296a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_type'], name='files_fileu_file_ty_bbbf1e_idx'),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='file_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='files.fileupload'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='file_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='files.fileupload'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='share_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='files.filesharelink'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['file_upload', '-timestamp'], name='files_filea_file_up_fbd201_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['user', '-timestamp'], name='files_filea_user_id_d25a41_idx'),
        ),
    ]
