# Generated by Django 4.2 on 2025-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileaccesslog_filesharelink_alter_fileupload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the file has been viewed'),
        ),
    ]
