# Generated by Django 4.2 on 2025-07-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_fileupload_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Last time file was modified'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='mime_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100),
        ),
    ]
