# Generated by Django 4.2 on 2025-07-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_fileupload_last_modified_fileupload_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Link to the original file if this is a duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='files.fileupload'),
        ),
    ]
