# Generated by Django 4.2 on 2025-07-06 07:44

from django.db import migrations

def standardize_file_types(apps, schema_editor):
    """
    Iterate over all FileUpload objects and standardize the file_type field
    to be a lowercase extension from the original_filename.
    """
    FileUpload = apps.get_model('files', 'FileUpload')
    for upload in FileUpload.objects.all():
        # Check if original_filename has an extension
        if '.' in upload.original_filename:
            # Extract extension, convert to lower, and save
            extension = upload.original_filename.rsplit('.', 1)[-1].lower()
            upload.file_type = extension
        else:
            # If no extension, mark as 'unknown'
            upload.file_type = 'unknown'
        upload.save(update_fields=['file_type'])

def revert_standardization(apps, schema_editor):
    """
    This is a data migration, and reverting it is not straightforward
    as the original state is not saved. We'll do nothing.
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_remove_fileaccesslog_share_link_delete_filesharelink'),
    ]

    operations = [
        migrations.RunPython(standardize_file_types, reverse_code=revert_standardization),
    ]
