# Generated by Django 4.2 on 2025-07-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_standardize_file_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_size'], name='files_fileu_file_si_8ffd86_idx'),
        ),
    ]
